language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
env:
  global:
    - HARNESS_OPTIONS=j4
    - TEST_EV=1
    - TEST_POD=1
install:
  - cpanm -n Mojolicious Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
